# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  latex-utilities = {
    pname = "latex-utilities";
    version = "0.4.9";
    src = fetchurl {
      url = "https://tecosaur.gallery.vsassets.io/_apis/public/gallery/publisher/tecosaur/extension/latex-utilities/0.4.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "latex-utilities-0.4.9.zip";
      sha256 = "sha256-QCC690iT0Zls0ks7A66QiURO8yRZ4no4e4Bxfg6Fwpo=";
    };
    publisher = "tecosaur";
  };
  nix-ide = {
    pname = "nix-ide";
    version = "0.2.1";
    src = fetchurl {
      url = "https://jnoortheen.gallery.vsassets.io/_apis/public/gallery/publisher/jnoortheen/extension/nix-ide/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-ide-0.2.1.zip";
      sha256 = "sha256-yC4ybThMFA2ncGhp8BYD7IrwYiDU3226hewsRvJYKy4=";
    };
    publisher = "jnoortheen";
  };
  vscode-pets = {
    pname = "vscode-pets";
    version = "1.22.0";
    src = fetchurl {
      url = "https://tonybaloney.gallery.vsassets.io/_apis/public/gallery/publisher/tonybaloney/extension/vscode-pets/1.22.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-pets-1.22.0.zip";
      sha256 = "sha256-0AVKNePQe8Kp0phxXefLKnWIH3SjIurUQlrnmEnMs2s=";
    };
    publisher = "tonybaloney";
  };
  vscode-yaml = {
    pname = "vscode-yaml";
    version = "1.11.10112022";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/vscode-yaml/1.11.10112022/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-yaml-1.11.10112022.zip";
      sha256 = "sha256-/ZD3LOf6d5dJJW7eGZgkrf4hj1CXZJNI0u06Bnmyo0Q=";
    };
    publisher = "redhat";
  };
}
